fixtures:
  repositories:
    apt:
      repo: 'git://github.com/puppetlabs/puppetlabs-apt'
      tag: '2.2.0'
    stdlib:
      repo: 'git://github.com/puppetlabs/puppetlabs-stdlib'
      tag: '3.2.0'
    concat:
      repo: 'git://github.com/puppetlabs/puppetlabs-concat'
      tag: '1.0.4'
    yum:
      repo: 'https://github.com/voxpupuli/puppet-yum.git'
      tag: '0.9.15'
  symlinks:
    'collectd': "#{source_dir}"
