---
notifications:
  email: false
sudo: false
language: ruby
bundler_args: --without system_tests
before_install: rm Gemfile.lock || true
script:
  - 'bundle exec rake test'
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 3.0" STRICT_VARIABLES="yes"
  - rvm: 2.1.6
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
  - rvm: 2.2.0
    env: PUPPET_VERSION="~> 4.0" STRICT_VARIABLES="yes"
deploy:
  provider: puppetforge
  user: puppet
  password:
    secure: ""
  on:
    tags: true
    # all_branches is required to use tags
    all_branches: true
    # Only publish if our main Ruby target builds
    rvm: 1.9.3
